# config.py

CAMERAS = [0]
CAMERA_BACKEND = "dshow"
CAMERA_WARMUP_FRAMES = 10
CAMERA_EMPTY_FRAME_TOLERANCE = 120
AUTO_DISCOVER_CAMERAS = True
CAMERA_SCAN_MAX_INDEX = 5
MAX_ACTIVE_CAMERAS = 2
PREFER_EXTERNAL_CAMERAS = True
BUILTIN_CAMERA_INDEX = 0

REID_THRESHOLD = 0.70
TRACK_STICKINESS_THRESHOLD = 0.58
FAULTY_MATCH_BOOST = 0.05
TRACKER_IOU_THRESHOLD = 0.35
TRACKER_MAX_MISSED = 20
RECENT_CROSS_CAMERA_SECONDS = 4
RECENT_MATCH_BOOST = 0.12
ID_SWITCH_MARGIN = 0.06
DUPLICATE_MERGE_THRESHOLD = 0.78

DB_NAME = "tracking.db"

MODEL_NAME = "osnet_x1_0"
