# config.py

CAMERAS = [0]
CAMERA_BACKEND = "dshow"
CAMERA_WARMUP_FRAMES = 10
CAMERA_EMPTY_FRAME_TOLERANCE = 120
AUTO_DISCOVER_CAMERAS = True
CAMERA_SCAN_MAX_INDEX = 5
MAX_ACTIVE_CAMERAS = 2
PREFER_EXTERNAL_CAMERAS = True
BUILTIN_CAMERA_INDEX = 0

REID_THRESHOLD = 0.82

DB_NAME = "tracking.db"

MODEL_NAME = "osnet_x1_0"
